sudo: required
services:
  - docker
env:
  global:   #this bariables can be used in all files as they are global
    - SHA=$(git rev-parse HEAD)    #it gets the latest $Git_SHA
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1   #it kills all prompts
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash> /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud component update kubectl
  - gcound auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-263421
  - gcloud config set compute/zone us-central-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password stdin
  - docker build -t bereketdeb/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true bereketdeb/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh