apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels: 
        component: server
    spec:
      containers:
        - name: server
          image: bereketdeb1/multi-server
          ports:
            - containerPort: 5000
          env: 
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgress-cluster-ip-service
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: '5432'
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword1   #name of the secret
                  key: PGPASSWORD   #key from the secret we created
